name: CI for GEB

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

permissions:
  id-token: write
  contents: read
  actions: write
  pull-requests: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - uses: yezz123/setup-uv@v4
        with:
          uv-venv: ".geb_venv"
      - run: uv pip install ruff
      - run: ruff format .
      - run: ruff check .
  # TODO: pytest
  # TODO: pyright
